version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000" 
    environment:
      NODE_ENV: production
      DB_STRING: mongodb://root:pass@mongodb:27017/mydatabase
      PORT: 4000

    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

  front-end:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
    depends_on:
      - server
    volumes:
      - ./front:/app
      - /app/node_modules/

volumes:
  mongodb_data: